### ISSUE TITLE
DragonFight unable to link to owner

### ISSUE THREAD

**Issue by PPGOME** [NerdNu/DragonFight#3]
Apologies if this is the wrong place to be submitting this.

I've been messing around with this for quite a bit, but haven't been able to get it to work. As the README says, the fight should link to the player who places the last crystal, but it doesn't. There are no errors in the console when the fight begins or is finished, except for the plugin simply saying `[DragonFight] [DragonFight LOG] But nobody owns the fight, so it doesn't count.` once a fight is completed.

I have attempted this on git-Paper-783 (1.16.5) and git-Purpur-1296 (1.17.1) (Fork of Tuinity, which is in turn a fork of Paper).

I am currently using the following plugins, but I have mix and matched different versions of them and got the same results.
- DragonFight v1.1.3
- BeastMaster v2.16.0 (Nerd fork)
- BlockStore v1.7.1
- EntityMeta v1.0.0 (Nerd fork)
- LibsDisguises Release 10.0.26
- ProtocolLib 4.7.0
- WorldEdit 7.2.6-beta-01+1415e6f
- WorldGuard 7.0.6-beta+10b66f3e

Entire section of DragonFight logs from beginning of fight to the end (I skipped to the end here, but the same happens when doing a full fight)
![image](https://user-images.githubusercontent.com/67039523/127818030-dbc0a673-7f4b-4346-bf02-d38469d174dd.png)

**Comment by LadyCailin** [comment]
I looked through the code, and this must be a bug  around FightState.java#1000. *Maybe* it should be changed to == 4, or >= 3. However, I'm not sure when the block placement actually happens in the model, maybe this isn't it.

![image](https://user-images.githubusercontent.com/647786/127863197-f76dd5b2-7c5c-4297-8bea-3f04c1c312a2.png)
Probably should throw it in a debugger or add additional logging, because I don't see the log message "The dragon was spawned by:" which should be displaying here, and is the only place that the fight owner is actually set. 

Unfortunately, I'm not able to build the jar right now, I'm missing too many dependencies, and don't have time to fix that right now. If anyone else can get it to build, I would suggest adding logging for each of the 3 conditions in the if statement, then seeing what that says, which should hopefully illuminate the issue.

**Comment by totemo** [comment]
I'll take it from here. It was certainly working in 1.15 and I haven't heard of this problem in 1.16.5 before, but I know that Paper has made some breaking changes in other areas as well. Perhaps Paper is no longer firing the event I was using to detect the final crystal placement.

**Comment by totemo** [comment]
It turned out to be overly restrictive conditions in my code for detecting when an end crystal is being placed to summon the dragon.

Fixed in v1.1.4.
